### PR TITLE
Do not track private browsing windows

### LINKED ISSUE #25: private browsing windows shouldn't be tracked
We need to either use or copy/paste some code out of PrivateBrowsingUtils.jsm module to test if the DOM window should be tracked or not.

https://dxr.mozilla.org/mozilla-beta/source/toolkit/modules/PrivateBrowsingUtils.jsm

### PR DESCRIPTION
**Pull request by rehandalal**
Fixes #25 

Depends on #20 

r?

### CODE REVIEW

**Review by mythmon — COMMENTED** [review]
r+, but lets wait to hear back about if we need this or not.

**Comment by rehandalal** [comment]
@lonnen already confirmed this is required.

**Comment by rehandalal** [comment]
From IRC:
> 5:00:14 PM <lonnen> "No data will be collected from inside Private Browsing windows."

**Comment by lonnen** [comment]
That's from the pioneer program ToS. It might be appropriate to implement
in pioneer-utils

**Pull request merged**
